name: Node CD
on:
  release:
    types: [created]
jobs:
  publish:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN}}
